# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
 
trigger:
- master

jobs:
- job: build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 4.4.1'
    inputs:
      versionSpec: 4.4.1

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
  
  - task: VSBuild@1
    displayName: 'Build solution Services/DataX.Flow/DataX.Flow.sln'
    inputs:
      solution: 'Services/DataX.Flow/DataX.Flow.sln'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.sourcesdirectory)/Services/DataX.Flow'
      ArtifactName: 'inferinput'
      publishLocation: 'Container'

- template: azure-pipelines-template.yml@templates
  parameters:
    dependsOn: 'build'
    ArtifactName: 'inferinput'

resources:
  repositories:
    - repository: templates
      type: git
      name: DevDiv/InferSharp